### ISSUE TITLE
Loading Data in Observable

### ISSUE THREAD

**Issue by spazznolo** [observablehq/datasets#6]
I'm learning how to work in Observable. My first task was to replicate the Calendar View graphic by forking the data into my account, and then calling the data from there. This did not work.

When I switch the observablehq address to ' require("@spazznolo/dji"); ', an error message appears (data = Ne: unable to load package.json).

**Comment by mbostock** [comment]
Hi spazznolo. The @observablehq/dji dataset refers to a package that was published to npm (by us). The source of the package is here:

https://github.com/observablehq/datasets/blob/master/dji/package.json

It is available on npm here (note that it does not have a README):

https://www.npmjs.com/package/@observablehq/dji

The reason that `require("@spazznolo/dji")` is presumably because you have not published a package of that name yourself to npm.

We recommend you host your data on GitHub Gist, as described in this tutorial:

https://beta.observablehq.com/@mbostock/introduction-to-data

If you have further questions, please use [our forum](https://talk.observablehq.com) to ask for help! Thank you.

**Comment by spazznolo** [comment]
Thanks so much for the quick, detailed response to my (clueless af) question, I appreciate it!
